In [2]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

In [11]:
df = pd.read_csv('M67-CG.csv')

In [12]:
df.head()

,RA_ICRS,DE_ICRS,Source,GLON,GLAT,plx,Gmag,BP-RP
0,132.946529,11.353877,5.990000e+17,216.231465,31.816583,1.2339,17.438314,2.049427
1,132.801300,11.310755,5.990000e+17,216.206608,31.669308,1.1585,13.923045,0.782881
2,132.951477,11.302159,5.990000e+17,216.289025,31.799104,1.1421,14.430771,0.861522
3,132.890835,11.380829,5.990000e+17,216.175575,31.778487,1.1938,12.622926,0.733996
4,132.794558,11.317111,5.990000e+17,216.196555,31.666007,1.1271,17.276985,1.737898

2. **Distance: $dist = \frac{1}{parallax}$**

In [13]:
df['dist'] = 1 / df['plx']

In [14]:
df.head()

,RA_ICRS,DE_ICRS,Source,GLON,GLAT,plx,Gmag,BP-RP,dist
0,132.946529,11.353877,5.990000e+17,216.231465,31.816583,1.2339,17.438314,2.049427,0.810438
1,132.801300,11.310755,5.990000e+17,216.206608,31.669308,1.1585,13.923045,0.782881,0.863185
2,132.951477,11.302159,5.990000e+17,216.289025,31.799104,1.1421,14.430771,0.861522,0.875580
3,132.890835,11.380829,5.990000e+17,216.175575,31.778487,1.1938,12.622926,0.733996,0.837661
4,132.794558,11.317111,5.990000e+17,216.196555,31.666007,1.1271,17.276985,1.737898,0.887233

3. **Absolute Magnitude and Luminosity**

In [15]:
df['Mag'] = df['Gmag'] + (5 * np.log10(df['plx']) -10)

In [16]:
df['L'] = 10 ** (0.4 * ( 4.83 - df['Mag']))

In [17]:
df.head()

,RA_ICRS,DE_ICRS,Source,GLON,GLAT,plx,Gmag,BP-RP,dist,Mag,L
0,132.946529,11.353877,5.990000e+17,216.231465,31.816583,1.2339,17.438314,2.049427,0.810438,7.894714,0.059445
1,132.801300,11.310755,5.990000e+17,216.206608,31.669308,1.1585,13.923045,0.782881,0.863185,4.242525,1.717869
2,132.951477,11.302159,5.990000e+17,216.289025,31.799104,1.1421,14.430771,0.861522,0.875580,4.719292,1.107346
3,132.890835,11.380829,5.990000e+17,216.175575,31.778487,1.1938,12.622926,0.733996,0.837661,3.007584,5.357553
4,132.794558,11.317111,5.990000e+17,216.196555,31.666007,1.1271,17.276985,1.737898,0.887233,7.536797,0.082657

4.

4. **Cluster Stars**

In [20]:
df['MS'] = df['L'].apply(lambda x: 1 if ((x > 2.5) and (x < 7.5)) else 0)

In [21]:
df.head()

,RA_ICRS,DE_ICRS,Source,GLON,GLAT,plx,Gmag,BP-RP,dist,Mag,L,MS
0,132.946529,11.353877,5.990000e+17,216.231465,31.816583,1.2339,17.438314,2.049427,0.810438,7.894714,0.059445,0
1,132.801300,11.310755,5.990000e+17,216.206608,31.669308,1.1585,13.923045,0.782881,0.863185,4.242525,1.717869,0
2,132.951477,11.302159,5.990000e+17,216.289025,31.799104,1.1421,14.430771,0.861522,0.875580,4.719292,1.107346,0
3,132.890835,11.380829,5.990000e+17,216.175575,31.778487,1.1938,12.622926,0.733996,0.837661,3.007584,5.357553,1
4,132.794558,11.317111,5.990000e+17,216.196555,31.666007,1.1271,17.276985,1.737898,0.887233,7.536797,0.082657,0

    5a. To calculate the mass and add it to the data for each star in the main sequence, given the quadrature calculated from Kramers' opacity law as k = k_0 * ρ * T^(-7/2), we need to use the formula for luminosity, L = 4 * π * R^2 * σ * T^4, where R is the radius and σ is the Stefan-Boltzmann constant.

    We can assume that all stars on the main sequence are in hydrostatic equilibrium, which means that the pressure gradient force is balanced by gravity. This implies that we can use the ideal gas law, PV = nRT, to relate the density ρ, temperature T, and pressure P.

    Then, we can use the p-p chain reaction to relate the luminosity L and mass M of the star. The p-p chain is the dominant energy source for stars with masses less than 1.2 solar masses.

In [27]:
# Constants
G = 6.6743e-11  # Gravitational constant in m^3 kg^-1 s^-2
sigma = 5.6704e-8  # Stefan-Boltzmann constant in W m^-2 K^-4
k0 = 1e-15  # Value of k0 for Kramers' opacity law

# Calculate Teff for each star using Bp-Rp color index and a color-temperature relation
df['teff'] = 4600 * (1 / (0.92 * df['BP-RP'] + 1.7) + 1 / (0.92 * df['BP-RP'] + 0.62))

# Calculate the mass for each star using Teff and luminosity
df['radius'] = np.sqrt(df['L'] / (4 * np.pi * sigma * df['teff']**4))
df['pressure'] = (df['L'] / (4 * np.pi * df['radius']**2 * df['teff']**4))**(1/3) * k0 * df['teff']**(7/2)
df['density'] = df['pressure'] / (1.38e-23 * df['teff'])
df['mass'] = df['L'] / (4 * np.pi * (df['radius']**2) * 3.846e26)

In [28]:
df

,RA_ICRS,DE_ICRS,Source,GLON,GLAT,plx,Gmag,BP-RP,dist,Mag,L,MS,teff,radius,pressure,mass,density
0,132.946529,11.353877,5.990000e+17,216.231465,31.816583,1.2339,17.438314,2.049427,0.810438,7.894714,0.059445,0,3118.935703,0.000030,0.000007,1.395180e-20,1.512429e+14
1,132.801300,11.310755,5.990000e+17,216.206608,31.669308,1.1585,13.923045,0.782881,0.863185,4.242525,1.717869,0,5332.823846,0.000055,0.000043,1.192431e-19,5.781651e+14
2,132.951477,11.302159,5.990000e+17,216.289025,31.799104,1.1421,14.430771,0.861522,0.875580,4.719292,1.107346,0,5101.868464,0.000048,0.000036,9.988987e-20,5.175853e+14
3,132.890835,11.380829,5.990000e+17,216.175575,31.778487,1.1938,12.622926,0.733996,0.837661,3.007584,5.357553,1,5487.982570,0.000091,0.000047,1.337381e-19,6.211416e+14
4,132.794558,11.317111,5.990000e+17,216.196555,31.666007,1.1271,17.276985,1.737898,0.887233,7.536797,0.082657,0,3467.549400,0.000028,0.000009,2.131548e-20,1.971131e+14
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
843,133.014778,11.689963,6.050000e+17,215.905555,32.018819,1.1435,12.585810,0.747308,0.874508,2.876991,6.042319,1,5444.784300,0.000098,0.000046,1.295768e-19,6.089905e+14
844,132.560995,11.741550,6.050000e+17,215.631112,31.637087,1.1247,14.946151,0.975459,0.889126,5.201334,0.710340,0,4802.443321,0.000043,0.000029,7.842480e-20,4.449533e+14
845,132.751692,11.901339,6.050000e+17,215.552255,31.873467,1.1313,16.751854,1.504415,0.883939,7.019743,0.133077,0,3786.877899,0.000030,0.000013,3.032003e-20,2.456756e+14
846,132.748510,11.735564,6.050000e+17,215.727950,31.801273,1.1991,14.437025,1.007396,0.833959,4.831302,0.998802,0,4725.050519,0.000053,0.000028,7.349034e-20,4.272430e+14
847,133.008264,11.998967,6.050000e+17,215.571172,32.142318,1.1027,16.179718,1.304351,0.906865,6.392005,0.237246,0,4113.673772,0.000034,0.000017,4.222054e-20,3.021575e+14

7. **HR diagram**